package dev.modernjava.upgrade.core;

public enum SourcePatternType {
    MAP_STRING_OBJECT,
    SIMPLE_DATE_FORMAT,
    EXECUTOR_FACTORY,
    THREAD_LOCAL,
    STRUCTURED_CONCURRENCY_PREVIEW,
    UNSAFE_MEMORY_ACCESS,
    JAVA_EE_REMOVED_API,
    JDK_INTERNAL_API,
    REFLECTIVE_ACCESS,
    SECURITY_MANAGER_USAGE,
    FINALIZATION_USAGE
}
